version: "3.3"

networks:
  api-network:

services:

  rest:
    image: 'rest-api:latest'
    restart: always
    ports:
      - 8081:8080
    environment:
      - spring.data.mongodb.uri=mongodb://mongo:27017/rest
    links:
      - mongo
    depends_on:
      - mongo
    networks:
      - api-network

  reactive:
    image: 'reactive-api:latest'
    restart: always
    ports:
      - 8082:8080
    environment:
      - spring.data.mongodb.uri=mongodb://mongo:27017/reactive
    links:
      - mongo
    depends_on:
      - mongo
    networks:
      - api-network

  graphql:
    image: 'graphql-api:latest'
    restart: always
    ports:
      - 8083:8080
    environment:
      - spring.data.mongodb.uri=mongodb://mongo:27017/graphql
    links:
      - mongo
    depends_on:
      - mongo
    networks:
      - api-network

  mongo:
    image: 'mongo:latest'
    restart: always
    networks:
      - api-network